interceptors
Yoga2014/Timesheet pull request #18
Opened 2024-02-02 16:48 UTC by AkashMT15

i have completed interceptors with token and pass successfully .

2024-02-04 04:10 UTC, Yoga2014 requested changes

2024-02-04 04:10 UTC, Yoga2014 commented on tvminfotech-employee-UI/src/app/auth.guard.ts
> +  constructor(private routes:Router ,public guarService:SignupService){}
correct the spelling guardService

2024-02-04 04:10 UTC, Yoga2014 commented on tvminfotech-employee-UI/src/app/login/login.component.ts
> -  debugger
remove all the debugger and push the changes

2024-02-04 04:10 UTC, Yoga2014 commented on tvminfotech-employee-services-main/src/main/resources/application.properties
> -spring.h2.console.enabled=true
resolve all the conflicts

2024-02-05 07:09 UTC, AkashMT15 commented
i have resolved all the mentioned issues mam

2024-02-05 07:10 UTC, merged